#!/usr/bin/env bash
# shellcheck disable=SC2034   # a profile exists to SET defaults; the engine is what reads them
#
# Profile: magento2 — served from pub/, with the build output kept out of the file sync.
#
# This is the profile the `container` strategy was designed for, so the reasoning is worth having in
# front of you, measured rather than assumed. The two Magento checkouts this was built against carry
# 90,093 and 79,252 files in vendor/.
#
# "Copy-on-write makes it free" is HALF TRUE and the half that is false is the expensive half: `cp -c`
# shares the data blocks, but it still has to create 79k directory entries and inodes, which timed at
# 52-60 SECONDS — not the "instant" the first draft of this design claimed. And that is only the
# beginning of the cost, because those 79k files then enter the file sync's watch set, per worktree,
# for as long as the worktree exists.
#
# Copying them inside the container instead timed at 45 seconds for the same tree — comparable up
# front, and it adds NOTHING to the sync set. That ongoing difference is the whole argument; the
# one-off numbers are close enough to be a wash.
#
# The exclusion is not configured separately; grove derives it from the two `container` lines below.
#
# EVERY PATH IS RELATIVE TO $GROVE_APP — the application root, as a prefix. Magento is not always at
# the repository root: one project here is a Magento checkout, another keeps Magento under docroot/
# with the repo holding tests and tooling alongside it. That single prefix is the whole difference
# between them, and it has to be a variable or this profile is wrong for one of the two:
#
#     GROVE_APP_ROOT="docroot"     # in .grove.conf, for the nested layout. Default: the repo root.

GROVE_DOCROOT="${GROVE_APP}pub"
GROVE_CONFIG_FILE="${GROVE_APP}app/etc/env.php"

GROVE_PATHS=(
	"${GROVE_APP}pub/media:clone"

	# Created, never copied: a cloned var/cache holds the other site's compiled configuration and
	# absolute paths, and pub/static holds its deployed theme files under content-hashed names.
	"${GROVE_APP}var/cache:empty"
	"${GROVE_APP}var/log:empty"
	"${GROVE_APP}var/page_cache:empty"
	"${GROVE_APP}var/session:empty"
	"${GROVE_APP}var/report:empty"
	"${GROVE_APP}pub/static:empty"

	# The two that earn the design. Copied INSIDE the container and excluded from sync.
	#
	# Set "vendor:fresh" in a project's .grove.conf to run `composer install` in the worktree instead.
	# The copy is fast and almost always right; it does couple the worktree to whatever the main
	# checkout had at that moment, which occasionally matters.
	"${GROVE_APP}vendor:container"
	"${GROVE_APP}generated:container"

	"${GROVE_APP}node_modules:link"
)

# Magento names its database in app/etc/env.php.
grove_profile_main_db() { # <main-root>
	sed -nE "s/.*'dbname'[[:space:]]*=>[[:space:]]*'([^']*)'.*/\1/p" "$1/${GROVE_APP}app/etc/env.php" 2>/dev/null | head -1
}

# env.php is rewritten for the database name only. Magento keeps its base URLs in core_config_data,
# which grove_db_seed already rewrote while the dump went past — so there is nothing else here that
# points at the main site.
#
# The cache and session prefixes ARE rewritten too where present: two Magento sites sharing one Redis
# or Memcached with the same prefix read each other's cached configuration, which presents as a
# worktree mysteriously serving the main site's settings.
grove_profile_write_config() { # <main-root> <wt-path> <name> <db> <local-host> <container-dir>
	local main_root="$1" wt="$2" name="$3" db="$4"
	local src="$main_root/${GROVE_APP}app/etc/env.php"
	[ -f "$src" ] || return 1
	mkdir -p "$wt/${GROVE_APP}app/etc" 2>/dev/null
	sed -E \
		-e "s|('dbname'[[:space:]]*=>[[:space:]]*')[^']*(')|\1$db\2|" \
		-e "s|('id_prefix'[[:space:]]*=>[[:space:]]*')[^']*(')|\1${name}_\2|" \
		"$src" >"$wt/${GROVE_APP}app/etc/env.php" 2>/dev/null
}

grove_profile_nginx_locations() {
	# Modelled on Magento's own nginx.conf.sample rather than invented. The static handling in
	# particular has to be exact: `pub/static` is an `empty` path in a worktree, so EVERY asset is
	# generated on demand by static.php — and static.php wants the resource WITHOUT the `/static/`
	# prefix and without the version segment. Passing it the full request path (the obvious-looking
	# `try_files ... /static.php?resource=$uri`) yields a 404 for every stylesheet and script, which
	# renders as an unstyled page rather than as an error.
	cat <<'EOF'
    location / {
        absolute_redirect off;
        try_files $uri $uri/ /index.php$is_args$args;
    }

    location /static/ {
        # Versioned paths are stripped, then anything not already on disk is generated by static.php.
        location ~ ^/static/version\d*/ {
            rewrite ^/static/version\d*/(.*)$ /static/$1 last;
        }
        if (!-f $request_filename) {
            rewrite ^/static/(version\d*/)?(.*)$ /static.php?resource=$2 last;
        }
        add_header X-Frame-Options "SAMEORIGIN";
    }

    location /media/ {
        try_files $uri $uri/ /get.php$is_args$args;
        location ~ ^/media/theme_customization/.*\.xml$ { deny all; }
        add_header X-Frame-Options "SAMEORIGIN";
    }

    location /errors/ {
        location ~* \.xml$ { deny all; }
    }

    location = /favicon.ico { access_log off; log_not_found off; }
    location = /robots.txt  { access_log off; log_not_found off; }
EOF
}

# Magento keeps its base URLs in the DATABASE, and redirects any request whose host does not match
# them. The seed rewrites hostnames textually, so a worktree inherits the main store's shape — and
# when that is the local ddev name, every request to the public name is answered with a 302 to a
# hostname that resolves only on this machine. The site is "up" and unreachable at the same time.
#
# So the worktree is told what it is called, and `redirect_to_base` is turned off for it: a dev
# worktree is legitimately reachable under two names, its local one and its public one, and bouncing
# between them helps nobody.
grove_profile_post_seed() { # <main-root> <wt-path> <name> <db> <public-url> <local-url>
	local db="$4" url="$5"
	printf "UPDATE core_config_data SET value='%s/' WHERE path IN ('web/unsecure/base_url','web/secure/base_url');
DELETE FROM core_config_data WHERE path='web/url/redirect_to_base';
INSERT INTO core_config_data (scope,scope_id,path,value) VALUES ('default',0,'web/url/redirect_to_base','0');
DELETE FROM core_config_data WHERE path LIKE 'web/%%base_link_url';\n" "$url" \
		| (cd "$MAIN_ROOT" && ddev mysql -uroot -proot "$db") >/dev/null 2>&1
}
